### ISSUE TITLE
Problems with Quark 1.20.1

### ISSUE THREAD

**Issue by SireAwfulThe1st** [ellie-semele/expanded-storage#5]
seems like ES is having problems with quark, so prolly ES gotta update tae be able tae run alongside quark I assume 
log is here
https://pastebin.com/BwnkyzNk

**Comment by ellie-semele** [comment]
Going to be honest, I haven't supported Forge in a while, and whilst this would be simple to fix otherwise I'm not sure if I have an easily restore-able code-base to edit from... Will see if I can rollback changes to provide a fix here but will let you know if that proves too difficult for me.

**Comment by ellie-semele** [comment]
https://modrinth.com/mod/expanded-storage/version/YErJ5xmx
