### ISSUE TITLE
Changing how pages looks (forgot configs)

### ISSUE THREAD

**Issue by SireAwfulThe1st** [ellie-semele/expanded-storage#6]
Not gonna lie, I forgot how to actually change the configs where the chest's GUI can be change between clickable pages or one long scrollable page, that is, I'm not sure what's the name of the scrollable page in the configs as there's no other example of other version other than the existing *"container_type": "expandedstorage:page",* for the clickable pages.

I know this is rather unimportant issue, but as far as I'm aware I'm not sure how I could contact you on other places other than GitHub as it seems like you do not link other places where you could be contacted like Discord, Twitter etc. So I hope this doesn't annoy you too much, pardon me ^^.

**Comment by ellie-semele** [comment]
Hey, in game you should be able to press `Shift + G` by default to open up the screen to change the screen type or if you have mod menu installed you should just be able to open it through that.

As for changing it manually in the config file, there's been a few changes to the type ids over time so I can't really provide the ones that will work for the version your using but here's all the options:

`expandedstorage:auto` - The default, opens up the screen to pick a screen type
`expandedstorage:single` - Tries to display every slot on the screen, can fail if gui scale too big or minecraft window size is too small.
`expandedstorage:page` or `expandedstorage:paginated` - Tries to maximize the amount of slots on screen whilst having those not visible in separate pages (off screen).
`expandedstorage:scoll` or `expandedstorage:scrollable` - Tries to maximize the amount of slots on screen whilst having those not visible as separate rows you can scroll to (off screen).

Hope this information helps, been trying to work on the project little by little and will make sure to have more of this documented on the modrinth mod page.

**Comment by SireAwfulThe1st** [comment]
Hey Ellie! thanks I honestly completely forgor I could do that lmfao, also thank you I'll try tae remember everything you said above too, and yes it's help alot and sorry for bothering tae ask here ^^. Have a nice day!
