### ISSUE TITLE
Server hangs during nether creation while using Incendium (1.20.4 Fabric)

### ISSUE THREAD

**Issue by redraskal** [ellie-semele/expanded-storage#7]
Hey, I found a weird issue with Expanded Storage while creating a modpack. Any ideas? I have yet to look at the source code. On the surface, I am confused as to why this mod would be problematic with a nether datapack.

**Mods:**
- Expanded Storage 12.0.0
- Fabric API 0.95.4+1.20.4
- Incendium 5.3.4 (technically a datapack, wrapped as a mod)

**To replicate:**
1. Create a default world with the seed 1951697667
2. Make a nether portal where you spawn
3. Enter portal
4. Server will hang

Nether will load upon removing Expanded Storage.

The crash reports are vague. It looks like net.minecraft.server.world.ServerChunkManager.getChunkBlocking() could be the source of the problem + something from net.minecraft.world.PortalForcer. I was thinking the server could not find a spot to place the portal in the nether but that does not seem relevant to this mod.

[crash-2024-02-09_02.40.33-server.txt](https://github.com/ellie-semele/expanded-storage/files/14217409/crash-2024-02-09_02.40.33-server.txt)

Also, the report had additional mods, but you can replicate this with just Incendium

**Comment by ellie-semele** [comment]
This sounds very strange, I'll look into and see if I can figure out the cause.

**Comment by ellie-semele** [comment]
Progress update, something in my data fixer code seems to be causing this, I don't really want to remove that code so it may take me a bit to figure out a proper fix...

**Comment by redraskal** [comment]
Thank you! I appreciate your work on the mod.
